### PR TITLE
Add fuzzing

### PR DESCRIPTION
**Pull request by sanmai-NL**
This helps improve robustness by discovering chrash-inducing bugs.

### CODE REVIEW

**Comment by jonhoo** [comment]
This is great! It'd be nice to also integrate this with testing somehow, but I'm guessing its runtime is too long to have it run every time?

**Comment by sanmai-NL** [comment]
Not yet, it has found bugs within a second. 😉

**Comment by sanmai-NL** [comment]
Fuzzing isn't deterministic, at least not without a corpus, is it? If so, then if we gate commits on fuzzing success, we can never be sure the same commit will pass during repeated runs.

Regardless, fuzzing [can be timed out](https://llvm.org/docs/LibFuzzer.html#options) after 120 seconds like so:

@jonhoo:
```sh
cargo +nightly-2017-10-05 fuzz run utf8_parse_response -- -max_total_time=120
```

**Comment by jonhoo** [comment]
Might then be worth adding it to the `.travis.yml` (though this repo doesn't have one yet :/) under `script` (see https://github.com/jonhoo/faktory-rs/blob/1849e6533d9b63720078ef77d963b04ee47fc52b/.travis.yml#L10)

**Comment by djc** [comment]
I ran 134217728 iterations, which got me to 1363 coverage, which was actually stable from iteration 3209528. So it seems there are no obvious crashes with ASCII-only input at least (after 0c854b5ca9f53d05999ba4152d44ec46c74409bc).

**Pull request merged**
