### PR TITLE
cleanup command builder

### PR DESCRIPTION
**Pull request by little-dude**
Mostly cosmetic changes. Creating Vec directly instead of creating an
empty one and then extending it, avoids needlessly resizing it but this
is probably a negligible improvement.

### CODE REVIEW

**Comment by djc** [comment]
Looks good, thanks!

**Comment by djc** [comment]
(After running `rustfmt`, I reverted some of the stylistic changes -- I'm trying to keep a consistent style as enforced by `rustfmt`. I should probably turn that into a unit test somehow...)

**Comment by little-dude** [comment]
ah, I did use rustfmt but probably not the same version then. Maybe there is a way to pin it in the Cargo.toml?

**Comment by djc** [comment]
You're right... I upgraded to recent `rustfmt-nightly` and the `struct_lit_width` option I was using is no longer supported. I've removed it (in 87fbb8f) and reverted the struct literal formatting to what you had before (in ffdd11c).

Pinning `rustfmt` might be tricky...

**Comment by little-dude** [comment]
Yeah it does not seem possible, but it's possible to run a specific version of rustfmt. `diesel` does that in travis: https://github.com/diesel-rs/diesel/blob/master/.travis.yml#L63

I think if you put in the README or in a CONTRIBUTING.md file which rustfmt version to use, people can use this one. Then, once in a while, you could bump the version.

**Comment by djc** [comment]
4d93a1f4d4e5c5ccdc2fa118554c9f699853c89b ensures checking with both clippy and rustfmt.

**Pull request merged**
