### PR TITLE
Add support for googles x-gm-labels extension

### PR DESCRIPTION
**Pull request by estriv**
Hi,

I was using your crate to interact with the Google IMAP server. As I heavily rely on [Google's IMAP extensions](https://developers.google.com/gmail/imap/imap-extensions) I started implementing them with X-GM-LABELS.

I would be glad if you accept the changes. Further implementation will be done as I find time and the need.

### CODE REVIEW

**Comment by link2xt** [comment]
Is it possible to also add some generic interface for unknown `X-` extensions, so `imap-proto` does not have to grow support for every non-standard extension?

Somewhat related PR, Delta Chat ignores `[Gmail]` folders mapped to these labels: https://github.com/deltachat/deltachat-core-rust/pull/2587

**Comment by estriv** [comment]
Yes this would be possible implementing a type for `MailboxDatum` and `AttributeValue` that holds a tag name (like "GM-LABELS" oder "GM-THRID") and a variant on a list, string or number. But this, in my eyes, breaks with the design choices of imap-proto as it softens the typing.

**Comment by estriv** [comment]
@djc What can I do?

**Comment by djc** [comment]
Have a little patience and not expect me to review your changes immediately when it's Christmas? 😛

**Comment by estriv** [comment]
Sorry, I thought I messed something up...

**Comment by djc** [comment]
Well, you should also run cargo fmt on your changes, looks like.

**Comment by estriv** [comment]
I already did this yesterday and pushed the changes: https://github.com/estriv/tokio-imap/commit/365c6e6971a288bfab9942bb92020e906193ebd9

**Comment by djc** [comment]
Well, that commit doesn't exist on your PR branch.

**Pull request closed without merging**
