### PR TITLE
Parse UIDPLUS response codes

### LINKED ISSUE #66: Support parsing RFC 4315 (UIDPLUS Extension) response codes
[`UIDPLUS`] is useful and desired for implementing any kind of heavy-duty IMAP synchronization tool (e.g., a RIIR of offlineimap). This requires parsing of three additional response codes: `COPYUID`, `APPENDUID`, and `UIDNOTSTICKY`.

[`UIDPLUS`]: https://tools.ietf.org/html/rfc4315

### PR DESCRIPTION
**Pull request by mmirate**
I believe this would fix #66.

### CODE REVIEW

**Comment by mmirate** [comment]
Seems your codecov.io integration is misconfigured?

**Comment by djc** [comment]
Thanks for working on this!

I believe the codecov CI will not work for PRs from forks, due to not wanting to expose the token to external contributors.

This mostly looks good. I generally prefer not to rely on `Either` enums, instead defining our own with domain-specific variants. Additionally, please add some docstrings to the new parsers that link to the relevant RFC and show the syntax definition for that particular parser (as is done in many of the existing parsers).

**Comment by mmirate** [comment]
... hmm. How do I monospace the ABNF without making cargo think it's a doctest?

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
I'm fine with the syntax definitions without monospace. 😊

**Pull request merged**
